version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.0.3
jobs:
  # build-and-push:
  #   executor: docker/docker
  #   steps:
  #     - setup_remote_docker
  #     - checkout
  #     - docker/check
  #     - docker/build:
  #         image: my_repo/orb-test
  #     - docker/push:
  #         digest-path: /tmp/digest.txt
  #         image: my_repo/orb-test
  #     - run:
  #         command: |
  #           echo "Digest is: $(</tmp/digest.txt)"
workflows:
  pipeline:
    jobs:
      - node/test
      # - build-and-push
