version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.0.3
jobs:
  build-and-push:
    executor: docker/docker
    environment: 
      - DOCKER_IMAGE: nvminh0810/cicd
      - IMAGE_TAG: latest
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - docker/check
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $IMAGE_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $IMAGE_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"
  deploy: 
    executor: docker/docker
    steps:
      - add_ssh_key:
          fingerprints:
            - "bd:2b:f0:7d:27:1a:44:67:3d:c3:e9:63:2e:ef:09:80"
      - run: ssh -o StrictHostKeyChecking=no parallels@10.211.55.6
workflows:
  pipeline:
    jobs:
      - node/test
      - build-and-push:
          requires:
            - node/test
          filters: 
            branches: 
              only: 
                - main 
